version: '3.8'

services:
    app:
        build:
            context: .
        ports:
            - 80:5001
        depends_on:
            db:
                condition: service_healthy
        env_file: .env
    db:
        image: postgres:15-alpine
        restart: always
        env_file: .env
        volumes:
            - db-data:/var/lib/postgres
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -d postgres -U postgres" ]
            interval: 10s
            timeout: 5s
            retries: 5

volumes:
    wean-db-data:
